USS Marlow
cmapplelings/cmreboot pull request #30
Opened 2023-11-02 20:42 UTC by Patternseeker

# About the pull request

Adds USS Marlow

# Explain why it's good for the game

almayer yucky

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added USS Marlow.
/:cl:

2023-11-03 14:51 UTC, Kitsunemitsu requested changes
Changes requested. Please Fix before merge.

2023-11-03 14:51 UTC, Kitsunemitsu commented on code/modules/projectiles/guns/rifles.dm
> -	start_automatic = TRUE
This is actually a balance change. Id' recommend atomizing this into a new pr.

2023-11-03 14:51 UTC, Kitsunemitsu commented on code/modules/projectiles/guns/rifles.dm
> +	set_fire_delay(FIRE_DELAY_TIER_6)
This is a mapping PR? Why are you buffing the M4RA.

2023-11-03 14:51 UTC, Kitsunemitsu commented on code/modules/projectiles/guns/rifles.dm
> +	burst_scatter_mult = SCATTER_AMOUNT_TIER_8
Are you adding burst too? This increases the damage of the M4RA significantly across long ranges. Do watch out for that.

2023-11-03 14:51 UTC, Kitsunemitsu commented on strings/ai.txt
> -Shrike
This is kinda entirely unrelated? 
I am in awe at how this got into this PR, and it shows a whole lack of care to this whole PR.

2023-11-04 17:08 UTC, Ireuldiz approved these changes
all is well- merging & making further edits upon this

2023-11-04 17:08 UTC, merged